services:
  - type: web
    name: lucy-lara-site
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_INCLUDE
        value: dev
    healthCheckPath: /api/health
